### Criar novo usuário
POST http://localhost:5000/api/users
Content-Type: application/json

{
  "name": "João pereira",
  "email": "joao@gmail.com",
  "password": "senha12345"
}

### Listar todos os usuários
GET http://localhost:5000/api/users

### Obter usuário por ID
GET http://localhost:5000/api/users/{}